name: Fever Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:  # allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # 4️⃣ Run Fever Bot
      - name: Run Fever Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python fever_bot.py

      # 5️⃣ Commit sent contests and log file back to repo
      - name: Commit Updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          # Directly embed PAT (unsafe!)
          git remote set-url origin https://x-access-token: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@github.com/karanisking/feverfm.git
          git add sent_contests.json fever_bot.log
          git commit -m "Update sent contests and log" || echo "No changes to commit"
          git push
